### ISSUE TITLE
Issue on some runs

### ISSUE THREAD

**Issue by holtjma** [inumanag/aldy#1]
Hello,

I'm running Aldy on some samples I have and almost all of them worked flawlessly for all the gene profiles that are available. However, I have two samples that are both failing to run _DPYD_ and they're receiving an identical error message:

```
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
*** Aldy v1.2 (Python 3.7.0) ***
(c) 2017 SFU, MIT & IUB. All rights reserved.
Arguments:
  Gene:      DPYD
  Profile:   illumina
  Threshold: 50%
  Input:     /data_mount/sample.bam
  Output:    /data_output/DPYD.aldy
  Log:       /data_output/DPYD.aldy.log
  Phasing:   False
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aldy/genotype.py", line 59, in genotype
    score, init_sol = protein.get_initial_solution(gene, sample, cn_sol, solver)
  File "/usr/local/lib/python3.7/site-packages/aldy/protein.py", line 44, in get_initial_solution
    structure
  File "/usr/local/lib/python3.7/site-packages/aldy/protein.py", line 235, in solve_ilp
    status, opt, solutions = c.solveAll(objective, dict(list(A.items()) + [((a, m), M[a][m]) for a in M for m in M[a]]))
  File "/usr/local/lib/python3.7/site-packages/aldy/lpinterface.py", line 157, in solveAll
    solutions = [tuple(sorted(y for y in x)) for x in solutions]
  File "/usr/local/lib/python3.7/site-packages/aldy/lpinterface.py", line 157, in <listcomp>
    solutions = [tuple(sorted(y for y in x)) for x in solutions]
TypeError: '<' not supported between instances of 'tuple' and 'str'
```

For setup, I'm running inside Docker using SCIP (I can send more if necessary).  Thoughts?

**Comment by holtjma** [comment]
I forgot to mention, the two samples that are failing _DPYD_ successfully ran all the other gene profiles available.

**Comment by inumanag** [comment]
I am looking into this and will let you know ASAP when I find the bug. Thanks for the report!

**Comment by lhon** [comment]
I ran into this as well previously, and the issue has to do with how python 3 does sorting--it has stricter requirements on the data structure compared to python 2. My workaround was to run using python 2 (via Docker). Here was the error I encountered when running against CYP2D6 using Python 3.5.2:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aldy/genotype.py", line 60, in genotype
    score, init_sol = protein.get_initial_solution(gene, sample, cn_sol, solver)
  File "/usr/local/lib/python3.5/dist-packages/aldy/protein.py", line 44, in get_initial_solution
    structure
  File "/usr/local/lib/python3.5/dist-packages/aldy/protein.py", line 235, in solve_ilp
    status, opt, solutions = c.solveAll(objective, dict(list(A.items()) + [((a, m), M[a][m]) for a in M for m in M[a]]))
  File "/usr/local/lib/python3.5/dist-packages/aldy/lpinterface.py", line 157, in solveAll
    solutions = [tuple(sorted(y for y in x)) for x in solutions]
  File "/usr/local/lib/python3.5/dist-packages/aldy/lpinterface.py", line 157, in <listcomp>
    solutions = [tuple(sorted(y for y in x)) for x in solutions]
TypeError: unorderable types: tuple() < str()
```

**Comment by inumanag** [comment]
I think I isolated this problem and the fix should be there soon. Thanks!

**Comment by inumanag** [comment]
Hi @holtjma ,

Can you try devel branch and let me know do you still have the same issue?
Don't forget to run aldy devel as

```
aldy genotype <old parameters>
```

Thanks!

**Comment by holtjma** [comment]
@inumanag, I ran into two issues:

1) It looks like the `-l LOG` parameter was removed somewhere.  I removed the parameter and it looks like it now defaults to saving a log file in the directory with the BAM file.  This is long-run a problem for me since that directory is generally read-only to protect data.  I found a work-around to get to the next issue.

2) I got a different error than before, copied below.  I also tested on one of the other genes (_CYP4F2_) and that one is failing now as well.
```
root@4ea8341a8a0c:/# aldy genotype --profile illumina --gene DPYD -o /data_output/DPYD.aldy /data_mount/sample.bam
*** Aldy v1.9 (Python 3.7.0) ***
*** (c) 2016-2018 Aldy Authors & Indiana University Bloomington. All rights reserved.
*** Free for non-commercial/academic use only.
Using 22:42546963-42548250 as copy-number neutral region
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
addVar() got an unexpected keyword argument 'update'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aldy/__main__.py", line 92, in main
    _genotype(gene, output, args)
  File "/usr/local/lib/python3.7/site-packages/aldy/__main__.py", line 264, in _genotype
    reference=   args.reference)
  File "/usr/local/lib/python3.7/site-packages/aldy/genotype.py", line 122, in genotype
    cn_sols = cn.estimate_cn(gene, sample.coverage, solver=solver, user_solution=cn_solution)
  File "/usr/local/lib/python3.7/site-packages/aldy/cn.py", line 130, in estimate_cn
    sol = solve_cn_model(gene, configs, max_observed_cn, region_cov, solver)
  File "/usr/local/lib/python3.7/site-packages/aldy/cn.py", line 227, in solve_cn_model
    coeffs={'E_{}{}'.format(*PCE_REGION): PCE_PENALTY_COEFF})
  File "/usr/local/lib/python3.7/site-packages/aldy/lpinterface.py", line 104, in abssum
    absvar = self.addVar(lb=0, update=False)
  File "/usr/local/lib/python3.7/site-packages/aldy/lpinterface.py", line 206, in addVar
    return self.model.addVar(*args, **kwargs)
  File "src/pyscipopt/scip.pyx", line 902, in pyscipopt.scip.Model.addVar
TypeError: addVar() got an unexpected keyword argument 'update'
```

**Comment by inumanag** [comment]
Oh sorry— log parameter is still there but must be specified before the genotype command 
(e.g. `aldy -l log.txt genotype ...`). This is temporary and will be fixed soon.

Can you give me a day or two to check the issue below? I haven't used SCIP for a long time and probably some update broke SCIP functionality. Will try to get that tested and resolved during the weekend.

**Comment by holtjma** [comment]
Yea, no problem at all, thanks for looking into it!  I can email the detailed log file if that will help at all.
 
I must've just missed the movement of the log file parameter when I was skimming the README, thanks for pointing out the change so I can modify.

**Comment by inumanag** [comment]
Both issues should be fixed. SCIP should work and now you can pass -l and -v after the command as well. Please let me know if it works so that I can close the issue.

**Comment by holtjma** [comment]
Alright, so the latest version is working again for CYP4F2 (as it did originally), but is still failing for DPYD for some reason:

```
*** Aldy v1.9 (Python 3.7.0) ***
*** (c) 2016-2018 Aldy Authors & Indiana University Bloomington. All rights reserved.
*** Free for non-commercial/academic use only.
Using 22:42546963-42548250 as copy-number neutral region
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
[W::hts_idx_load2] The index file is older than the data file: /data_mount/sample.bam.bai
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
Potential copy number configurations for DPYD:
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
   1: 2x*1
Potential major star-alleles for DPYD:
   1: 1x*5, 1x*6 +98348884:SNP.AG*
   2: 1x*5 +97770919:SNP.CT*, 1x*9
   3: 1x*5 +98348884:SNP.AG*, 1x*6
   4: 1x*5, 1x*9 +97770919:SNP.CT*
   5: 1x*6, 1x*9 +97981394:SNP.TC*
Gurobi not found. Please install Gurobi and gurobipy Python package.
No module named 'gurobipy'
Nonlinear objective functions are not supported!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aldy/__main__.py", line 92, in main
    _genotype(gene, output, args)
  File "/usr/local/lib/python3.7/site-packages/aldy/__main__.py", line 267, in _genotype
    reference=   args.reference)
  File "/usr/local/lib/python3.7/site-packages/aldy/genotype.py", line 156, in genotype
    minor_sols = minor.estimate_minor(gene, sample.coverage, major_sols, solver)
  File "/usr/local/lib/python3.7/site-packages/aldy/minor.py", line 107, in estimate_minor
    minor_sols.append(solve_minor_model(gene, alleles, cov, major_sol, mutations, solver))
  File "/usr/local/lib/python3.7/site-packages/aldy/minor.py", line 331, in solve_minor_model
    status, opt = model.solve(objective)
  File "/usr/local/lib/python3.7/site-packages/aldy/lpinterface.py", line 218, in solve
    'minimize' if method == 'min' else 'maximize'
  File "src/pyscipopt/scip.pyx", line 782, in pyscipopt.scip.Model.setObjective
ValueError: Nonlinear objective functions are not supported!
```

**Comment by inumanag** [comment]
Let me fetch the DPYD data and  try to reproduce it. Which scip version are you using btw?

**Comment by holtjma** [comment]
It's SCIP version 6.0.0 and pyscipopt version 2.0.1

**Comment by inumanag** [comment]
1) Any chance you can send me Aldy log (with -vD)? I could not reproduce the issue on DPYD. E-mail is inumanag at mit dot edu.
1) Also, can you stick with Aldy v1.2 for now? I just pushed a patch that should fix the original bug. I found another issue with 1.9 on DPYD which is bit serious (esp. on SCIP; 1.2 should work fine).

**Comment by holtjma** [comment]
email just sent
